FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o task-tower-worker cmd/worker/main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

USER appuser

WORKDIR /home/appuser

COPY --from=builder /app/task-tower-worker .
COPY --from=builder /app/config/release-config.yml ./config/config.yml
ENV GIN_MODE=release
CMD ["./task-tower-worker"]