POST localhost:5000/execute

{
    "Parameters": {
        "moje_imie" : "Jan",
        "czesc.name": "Piotr",
        "cze.name": "Marian i {{czesc.name}}",
        "czes.name": "{{czesc.name}} i {{cze.name}} oraz sw {{moje_imie}}"
    },
    "Stages": [
        {
            "Sequence": 1,
            "Name": "czesc",
            "Action": "hallo"
        },
        {
            "Sequence": 2,
            "Name": "cze",
            "Action": "hallo"
        },
        {
            "Sequence": 3,
            "Name": "czes",
            "Action": "hallo"
        }
    ]
}


###

POST localhost:5000/execute

{
   "Parameters":{
      "numbers.a":"1",
      "numbers.b":"2",
      "wynik.text":"{{numbers.a}} + {{numbers.b}} = {{numbers.c}}",
      "petla.collection":"[{a : 1},{a : 2},{a : 3}]"
   },
   "Stages":[
      {
         "Sequence":1,
         "Name":"numbers",
         "Action":"add-numbers"
      },
      {
         "Sequence":2,
         "Name":"wynik",
         "Action":"console"
      },
      {
         "Sequence":3,
         "Name":"petla",
         "Action":"for-each",
         "SubPipeline":{
            "Parameters":{
               "for-wynik.text":"petla.a"
            },
            "Stages":[
               {
                  "Sequence":1,
                  "Name":"for-wynik",
                  "Action":"console"
               }
            ]
         }
      }
   ]
}

###

POST localhost:5000/execute

{
    "Parameters": {
        "clone.url" : "https://github.com/PiotrFerenc/mash2",
        "console.text":"repo znajduje się w {{clone.path}}"
    },
    "Stages": [
        {
            "Sequence": 1,
            "Name": "clone",
            "Action": "git-clone"
        }
         ,{
            "Sequence": 2,
            "Name": "console",
            "Action": "console"
        }
    ]
}
