POST localhost:5000/execute

{
    "Parameters": {
        "moje_imie" : "Jan",
        "czesc.name": "Piotr",
        "cze.name": "Marian i {{czesc.name}}",
        "czes.name": "{{czesc.name}} i {{cze.name}} oraz sw {{moje_imie}}"
    },
    "Stages": [
        {
            "Order": 1,
            "Name": "czesc",
            "Action": "hallo"
        },
        {
            "Order": 2,
            "Name": "cze",
            "Action": "hallo"
        },
        {
            "Order": 3,
            "Name": "czes",
            "Action": "hallo"
        }
    ]
}


###

POST localhost:5000/execute

{
    "Parameters": {
        "numbers.a" : "1",
        "numbers.b": "2",
        "wynik.text": "{{numbers.a}} + {{numbers.b}} = {{numbers.c}}"
    },
    "Stages": [
        {
            "Order": 1,
            "Name": "numbers",
            "Action": "addnumbers"
        },{
            "Order": 2,
            "Name": "wynik",
            "Action": "console"
        }
    ]
}

###

POST localhost:5000/execute

{
    "Parameters": {
        "clone.url" : "https://github.com/PiotrFerenc/mash2",
        "console.text":"repo znajduje się w {{clone.path}}"
    },
    "Stages": [
        {
            "Order": 1,
            "Name": "clone",
            "Action": "git-clone"
        }
         ,{
            "Order": 2,
            "Name": "console",
            "Action": "console"
        }
    ]
}
