POST localhost:5000/execute

{
    "Parameters": {
        "moje_imie" : "Jan",
        "czesc.text": "Piotr",
        "cze.text": "Marian i {{czesc.text}}",
        "czes.text": "{{czesc.text}} i {{cze.text}} oraz sw {{moje_imie}}"
    },
    "Tasks": [
        {
            "Sequence": 1,
            "Name": "czesc",
            "Action": "console"
        },
        {
            "Sequence": 2,
            "Name": "cze",
            "Action": "console"
        },
        {
            "Sequence": 3,
            "Name": "czes",
            "Action": "console"
        }
    ]
}
###
GET http://localhost:5000/process/cbff06d2-24a2-40e5-9b3e-bcd9aaaabd7f

###

POST localhost:5000/execute

{
   "Parameters":{
      "numbers.a":"1",
      "numbers.b":"2",
      "wynik.text":"{{numbers.a}} + {{numbers.b}} = {{numbers.c}}",
      "petla.collection":"{\"items\":[{\"a\" : 1},{\"a\" : 2},{\"a\" : 3}]}",
      "petla.collectionKeyName":"items"
   },
   "Tasks":[
      {
         "Sequence":1,
         "Name":"numbers",
         "Action":"add-numbers"
      },
      {
         "Sequence":2,
         "Name":"wynik",
         "Action":"console"
      },
      {
         "Sequence":3,
         "Name":"petla",
         "Action":"for-each",
         "body":{
            "Parameters":{
               "for-wynik.text":"petla.a"
            },
            "Tasks":[
               {
                  "Sequence":1,
                  "Name":"for-wynik",
                  "Action":"console"
               }
            ]
         }
      }
   ]
}

###

POST localhost:5000/execute

{
    "Parameters": {
        "clone.url" : "https://github.com/PiotrFerenc/mash2",
        "console.text":"repo znajduje się w {{clone.path}}"
    },
    "Tasks": [
        {
            "Sequence": 1,
            "Name": "clone",
            "Action": "git-clone"
        }
         ,{
            "Sequence": 2,
            "Name": "console",
            "Action": "console"
        }
    ]
}
###

POST localhost:5000/execute

{
    "Parameters": {
        "docker.image" : "dotnet-classlib",
        "docker.e" : "PROJECT_NAME=MyCustomProject2",
        "docker.v" : "\"$(pwd)/hostFolder:/data\"",
        "console.text":"container id: {{docker.id}}"
    },
    "Tasks": [
        {
            "Sequence": 1,
            "Name": "docker",
            "Action": "docker-run"
        }
         ,{
            "Sequence": 2,
            "Name": "console",
            "Action": "console"
        }
    ]
}
###

POST localhost:5000/execute

{
    "Parameters": {
       "console.text":"hallo word"
    },
    "Tasks": [
        {
            "Sequence": 1,
            "Name": "log",
            "Action": "console"
        }
    ]
}
